# pipelines travis-ci config

language: python
python:
  - "2.6"
  # - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "3.6"
  # - "nightly"

install:
  - "pip install -r requirements.txt"

script:
  - "make test"
  - "make pep8"
